name: Sync submodule pointer in DDC-Canon

on:
  workflow_dispatch:

jobs:
  update-canon:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout DDC-Canon repo
        uses: actions/checkout@v3
        with:
          repository: Day-Dream-Company/DDC-Canon
          token: ${{ secrets.DDC_CANON_ACTIONS }}
          ref: main
          path: canon

      - name: Update submodule pointer
        run: |
          cd canon
          git config user.name "DDC-Canon Actions"
          git config user.email "bot@daydream.company"
          git config --global url."https://x-access-token:${{ secrets.DDC_CANON_ACTIONS }}@github.com/".insteadOf "https://github.com/"
          
          git submodule update --init --recursive
          cd source/content-submodule
          git checkout main
          git pull origin main
          cd ../..
          git add source/content-submodule
          git commit -m "Update submodule to latest commit on main"
          git push origin main